spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  config:
    import:
      - classpath:redis-prefix.yml
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true



logging:
  level:
    root: INFO
    com.localcoupon: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: DEBUG
    com.zaxxer.hikari: INFO
